# frozen_string_literal: true

require_relative "database"
require_relative "../lib/models/card"

CARD_NAMES = [
  "selfless spirit",
  "giver of runes",
  "thraben inspector",
  "luminarch aspirant",
  "adeline, resplendent cathar",
  "thalia, guardian of thraben",
  "blade splicer",
  "skyclave apparition",
  "gideon blackblade",
  "path to exile",
  "winds of abandon",
  "snapcaster mage",
  "thassa, deep-dwelling",
  "tezzeret, artifice master",
  "counterspell",
  "memory lapse",
  "remand",
  "memory deluge",
  "frantic search",
  "preordain",
  "serum visions",
  "stitcher's supplier",
  "sedgemoor witch",
  "rankle, master of pranks",
  "liliana, the last hope",
  "liliana of the veil",
  "urza, lord high artificer",
  "infernal grasp",
  "baleful mastery",
  "unearth",
  "cavalier of flame",
  "lightning bolt",
  "unholy heat",
  "birds of paradise",
  "elvish reclaimer",
  "ignoble hierarch",
  "noble hierarch",
  "questing beast",
  "titania, protector of argoth",
  "once upon a time",
  "nature's lore",
  "harrow",
  "esika's chariot",
  "spell queller",
  "baleful strix",
  "master of death",
  "falkenrath aristocrat",
  "atarka's command",
  "manamorphose",
  "voice of resurgence",
  "knight of the reliquary",
  "izzet charm",
  "prismari command",
  "deathrite shaman",
  "grim flayer",
  "grist, the hunger tide",
  "the gitrog monster",
  "hydroid krasis",
  "hangarback walker",
  "phyrexian revoker",
  "phyrexian metamorph",
  "golos, tireless pilgrim",
  "ugin, the ineffable",
  "liquimetal torque",
  "talisman of creativity",
  "talisman of dominance",
  "talisman of indulgence",
  "throne of the god-pharaoh",
  "coalition relic",
  "nettlecyst",
  "celestial colonnade",
  "flooded strand",
  "creeping tar pit",
  "polluted delta",
  "blood crypt",
  "kessig wolf run",
  "raging ravine",
  "stomping ground",
  "wooded foothills",
  "godless shrine",
  "breeding pool",
  "ketria triome",
  "urza's saga",
  "hallowed spiritkeeper",
  "persist",
  "bedlam reveler",
  "cemetery prowler",
  "cemetery gatekeeper",
  "wrenn and six",
  "cemetery illuminator",
  "ranger-captain of eos",
  "manaform hellkite",
  "god-eternal bontu",
  "flame slash",
  "primeval titan",
  "jolrael, mwonvuli recluse",
  "esper sentinel",
  "sprite dragon",
  "crucible of worlds",
  "damnation",
  "magmatic sinkhole",
  "bitterblossom",
  "archmage's charm",
  "Stormwing Entity",
  "call the coppercoats",
  "cave of the frost dragon",
  "hall of storm giants",
  "mana leak",
  "doom whisperer",
  "callous bloodmage",
  "dreadhorde invasion",
  "monastery swiftspear",
  "soul-scar mage",
  "legion warboss",
  "magma jet",
  "den of the bugbear",
  "elder gargaroth",
  "biogenic ooze",
  "eternal witness",
  "paradise druid",
  "lingering souls",
  "escape to the wilds",
  "sai, master thopterist",
  "sphinx's revelation",
  "trostani discordant",
  "aurelia, exemplar of justice",
  "growth spiral",
  "wurmcoil engine",
  "mana confluence",
  "prismatic vista",
  "fabled passage",
  "expedition map"
].freeze

DB.transaction do
  CARD_NAMES.each { Card.create(name: _1) }
end
